In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving customer_data.csv to customer_data (1).csv
Saving inventory_data.csv to inventory_data (1).csv
Saving product_data.csv to product_data (1).csv
Saving sales_data.csv to sales_data (1).csv

In [ ]:
customer_df = pd.read_csv("customer_data.csv")
inventory_df = pd.read_csv("inventory_data.csv")
product_df = pd.read_csv("product_data.csv")
sales_df = pd.read_csv("sales_data.csv")

In [ ]:
print("Customer Data:", customer_df.shape)
print("Inventory Data:", inventory_df.shape)
print("Product Data:", product_df.shape)
print("Sales Data:", sales_df.shape)

Customer Data: (500, 13)
Inventory Data: (4803, 8)
Product Data: (80, 6)
Sales Data: (5000, 19)

In [ ]:
customer_df.head()

,Customer_ID,Customer_Name,Age,Gender,City,Customer_Segment,Registration_Date,Total_Orders,Total_Spending,Last_Purchase_Date,Total_Profit,Days_Since_Last_Purchase,Churn_Status
0,C1000,Ishita_1,46,Male,Varanasi,Premium,13/03/2023,10,68118.0,17/03/2026,16472.0,105,No
1,C1001,Arjun_2,36,Male,Mumbai,Occasional,03/04/2024,4,45288.0,18/06/2025,11087.0,377,Yes
2,C1002,Rohan_3,41,Female,Agra,Occasional,05/11/2023,4,19915.0,17/05/2026,5582.0,44,No
3,C1003,Rohan_4,19,Male,Prayagraj,Premium,04/10/2023,7,44905.0,01/08/2025,10376.0,333,Yes
4,C1004,Meera_5,44,Female,Gurugram,Regular,12/11/2024,16,81544.5,30/09/2025,23769.5,273,Yes

In [ ]:
inventory_df.head()

,Date,Product_ID,Product_Name,Category,Opening_Stock,Units_Sold,Stock_Received,Closing_Stock
0,01/01/2024,P115,Bluetooth Speaker V1,Electronics,251,1,4,254
1,01/01/2024,P125,Desk Lamp V2,Office,265,1,1,265
2,01/01/2024,P130,File Folder V1,Office,351,4,5,352
3,01/01/2024,P136,Water Bottle V1,Home,329,1,2,330
4,01/01/2024,P151,Cleaning Kit V1,Home,157,4,6,159

In [ ]:
product_df.head()

,Product_ID,Product_Name,Category,Cost_Price,Selling_Price,Initial_Stock
0,P100,Wireless Mouse V1,Electronics,2246,3130,131
1,P101,Wireless Mouse V2,Electronics,2270,2890,155
2,P102,Wireless Mouse V3,Electronics,2684,3210,228
3,P103,Keyboard V1,Electronics,2634,4190,165
4,P104,Keyboard V2,Electronics,576,820,261

In [ ]:
sales_df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Selling_Price,Cost_Price,Discount_Percent,Gross_Sales,Discount_Amount,Revenue,Total_Cost,Profit,Profit_Margin_Percent,Payment_Mode,Sales_Channel,City
0,ORD100000,22/02/2026,C1082,P150,LED Bulb V3,Home,1,2960,2119,10.0,2960,296.0,2664.0,2119,545.0,20.46,Card,Online,Noida
1,ORD100001,05/05/2024,C1052,P174,Coffee V3,Grocery,1,1420,1012,15.0,1420,213.0,1207.0,1012,195.0,16.16,Cash,Online,Kanpur
2,ORD100002,09/03/2024,C1117,P158,Phone Case V2,Accessories,1,2660,1753,5.0,2660,133.0,2527.0,1753,774.0,30.63,UPI,Store,Kanpur
3,ORD100003,12/07/2025,C1166,P167,Desk Mat V2,Accessories,3,3170,2059,10.0,9510,951.0,8559.0,6177,2382.0,27.83,Card,Store,Lucknow
4,ORD100004,07/02/2025,C1028,P123,Office Chair V3,Office,3,4680,3454,10.0,14040,1404.0,12636.0,10362,2274.0,18.00,Net Banking,Online,Lucknow

In [ ]:
print("CUSTOMER DATA")
customer_df.info()

print("\nINVENTORY DATA")
inventory_df.info()

print("\nPRODUCT DATA")
product_df.info()

print("\nSALES DATA")
sales_df.info()

CUSTOMER DATA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Customer_ID               500 non-null    object
 1   Customer_Name             500 non-null    object
 2   Age                       500 non-null    int64
 3   Gender                    500 non-null    object
 4   City                      500 non-null    object
 5   Customer_Segment          500 non-null    object
 6   Registration_Date         500 non-null    object
 7   Total_Orders              500 non-null    int64
 8   Total_Spending            500 non-null    float64
 9   Last_Purchase_Date        500 non-null    object
 10  Total_Profit              500 non-null    float64
 11  Days_Since_Last_Purchase  500 non-null    int64
 12  Churn_Status              500 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 50.9+ KB

INVENTORY DATA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            4803 non-null   object
 1   Product_ID      4803 non-null   object
 2   Product_Name    4803 non-null   object
 3   Category        4803 non-null   object
 4   Opening_Stock   4803 non-null   int64
 5   Units_Sold      4803 non-null   int64
 6   Stock_Received  4803 non-null   int64
 7   Closing_Stock   4803 non-null   int64
dtypes: int64(4), object(4)
memory usage: 300.3+ KB

PRODUCT DATA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     80 non-null     object
 1   Product_Name   80 non-null     object
 2   Category       80 non-null     object
 3   Cost_Price     80 non-null     int64
 4   Selling_Price  80 non-null     int64
 5   Initial_Stock  80 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.9+ KB

SALES DATA
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Order_ID               5000 non-null   object
 1   Order_Date             5000 non-null   object
 2   Customer_ID            5000 non-null   object
 3   Product_ID             5000 non-null   object
 4   Product_Name           5000 non-null   object
 5   Category               5000 non-null   object
 6   Quantity               5000 non-null   int64
 7   Selling_Price          5000 non-null   int64
 8   Cost_Price             5000 non-null   int64
 9   Discount_Percent       4992 non-null   float64
 10  Gross_Sales            5000 non-null   int64
 11  Discount_Amount        5000 non-null   float64
 12  Revenue                5000 non-null   float64
 13  Total_Cost             5000 non-null   int64
 14  Profit                 5000 non-null   float64
 15  Profit_Margin_Percent  5000 non-null   float64
 16  Payment_Mode           5000 non-null   object
 17  Sales_Channel          5000 non-null   object
 18  City                   4988 non-null   object
dtypes: float64(5), int64(5), object(9)
memory usage: 742.3+ KB

In [ ]:
print("Customer Missing Values:")
print(customer_df.isnull().sum())

print("\nInventory Missing Values:")
print(inventory_df.isnull().sum())

print("\nProduct Missing Values:")
print(product_df.isnull().sum())

print("\nSales Missing Values:")
print(sales_df.isnull().sum())

Customer Missing Values:
Customer_ID                 0
Customer_Name               0
Age                         0
Gender                      0
City                        0
Customer_Segment            0
Registration_Date           0
Total_Orders                0
Total_Spending              0
Last_Purchase_Date          0
Total_Profit                0
Days_Since_Last_Purchase    0
Churn_Status                0
dtype: int64

Inventory Missing Values:
Date              0
Product_ID        0
Product_Name      0
Category          0
Opening_Stock     0
Units_Sold        0
Stock_Received    0
Closing_Stock     0
dtype: int64

Product Missing Values:
Product_ID       0
Product_Name     0
Category         0
Cost_Price       0
Selling_Price    0
Initial_Stock    0
dtype: int64

Sales Missing Values:
Order_ID                  0
Order_Date                0
Customer_ID               0
Product_ID                0
Product_Name              0
Category                  0
Quantity                  0
Selling_Price             0
Cost_Price                0
Discount_Percent          8
Gross_Sales               0
Discount_Amount           0
Revenue                   0
Total_Cost                0
Profit                    0
Profit_Margin_Percent     0
Payment_Mode              0
Sales_Channel             0
City                     12
dtype: int64

In [ ]:
print("Rows with missing Discount_Percent:")
display(sales_df[sales_df["Discount_Percent"].isnull()])

print("\nRows with missing City:")
display(sales_df[sales_df["City"].isnull()])

Rows with missing Discount_Percent:

,Order_ID,Order_Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Selling_Price,Cost_Price,Discount_Percent,Gross_Sales,Discount_Amount,Revenue,Total_Cost,Profit,Profit_Margin_Percent,Payment_Mode,Sales_Channel,City
929,ORD100929,25/04/2025,C1434,P106,Headphones V1,Electronics,2,4570,3663,NaN,9140,1371.0,7769.0,7326,443.0,5.70,Net Banking,Online,Kanpur
1471,ORD101471,29/04/2024,C1024,P124,Desk Lamp V1,Office,1,4350,2868,NaN,4350,652.5,3697.5,2868,829.5,22.43,UPI,Online,Mumbai
1916,ORD101916,15/06/2025,C1491,P171,Travel Pouch V3,Accessories,1,1430,1156,NaN,1430,214.5,1215.5,1156,59.5,4.90,UPI,Phone,Noida
1918,ORD101918,15/08/2025,C1355,P106,Headphones V1,Electronics,5,4570,3663,NaN,22850,1142.5,21707.5,18315,3392.5,15.63,Card,Store,Noida
3566,ORD103566,22/11/2024,C1148,P164,Power Bank V2,Accessories,7,1150,849,NaN,8050,1207.5,6842.5,5943,899.5,13.15,UPI,Online,Delhi
3995,ORD103995,16/05/2026,C1371,P114,Webcam V3,Electronics,1,3680,2607,NaN,3680,184.0,3496.0,2607,889.0,25.43,Cash,Phone,Lucknow
4111,ORD104111,28/11/2025,C1491,P160,Charging Cable V1,Accessories,4,3270,2329,NaN,13080,654.0,12426.0,9316,3110.0,25.03,UPI,Online,Noida
4252,ORD104252,24/07/2025,C1402,P169,Travel Pouch V1,Accessories,3,2560,1733,NaN,7680,0.0,7680.0,5199,2481.0,32.30,UPI,Phone,Jaipur

Rows with missing City:

,Order_ID,Order_Date,Customer_ID,Product_ID,Product_Name,Category,Quantity,Selling_Price,Cost_Price,Discount_Percent,Gross_Sales,Discount_Amount,Revenue,Total_Cost,Profit,Profit_Margin_Percent,Payment_Mode,Sales_Channel,City
792,ORD100792,19/04/2024,C1474,P162,Charging Cable V3,Accessories,1,3240,2132,5.0,3240,162.0,3078.0,2132,946.0,30.73,UPI,Store,NaN
932,ORD100932,03/05/2025,C1406,P159,Phone Case V3,Accessories,4,1360,849,5.0,5440,272.0,5168.0,3396,1772.0,34.29,UPI,Store,NaN
1179,ORD101179,24/02/2024,C1065,P125,Desk Lamp V2,Office,3,4970,3317,5.0,14910,745.5,14164.5,9951,4213.5,29.75,UPI,Online,NaN
1185,ORD101185,10/03/2026,C1261,P125,Desk Lamp V2,Office,1,4970,3317,10.0,4970,497.0,4473.0,3317,1156.0,25.84,Card,Store,NaN
1852,ORD101852,14/01/2026,C1089,P173,Coffee V2,Grocery,1,930,610,10.0,930,93.0,837.0,610,227.0,27.12,Card,Online,NaN
2701,ORD102701,24/04/2025,C1400,P157,Phone Case V1,Accessories,1,560,464,0.0,560,0.0,560.0,464,96.0,17.14,Cash,Store,NaN
2735,ORD102735,23/03/2024,C1026,P176,Tea V2,Grocery,5,920,750,10.0,4600,460.0,4140.0,3750,390.0,9.42,Card,Store,NaN
2764,ORD102764,10/04/2026,C1021,P178,Biscuits V1,Grocery,1,1460,1162,0.0,1460,0.0,1460.0,1162,298.0,20.41,Cash,Online,NaN
3499,ORD103499,06/03/2024,C1042,P161,Charging Cable V2,Accessories,1,2440,1541,5.0,2440,122.0,2318.0,1541,777.0,33.52,UPI,Store,NaN
3814,ORD103814,09/01/2024,C1383,P136,Water Bottle V1,Home,1,1430,1182,0.0,1430,0.0,1430.0,1182,248.0,17.34,UPI,Online,NaN
3922,ORD103922,02/10/2024,C1231,P106,Headphones V1,Electronics,2,4570,3663,5.0,9140,457.0,8683.0,7326,1357.0,15.63,UPI,Online,NaN
4767,ORD104767,27/08/2024,C1412,P173,Coffee V2,Grocery,3,930,610,0.0,2790,0.0,2790.0,1830,960.0,34.41,Card,Online,NaN

In [ ]:
# Fill missing Discount_Percent using existing sales values

sales_df["Discount_Percent"] = sales_df["Discount_Percent"].fillna(
    (sales_df["Discount_Amount"] / sales_df["Gross_Sales"]) * 100
)

# Check
print("Missing Discount_Percent after cleaning:",
      sales_df["Discount_Percent"].isnull().sum())

Missing Discount_Percent after cleaning: 0

In [ ]:
# Create Customer_ID -> City mapping
customer_city = customer_df.set_index("Customer_ID")["City"]

# Fill missing City values using Customer_ID
sales_df["City"] = sales_df["City"].fillna(
    sales_df["Customer_ID"].map(customer_city)
)

# Check
print("Missing City after cleaning:",
      sales_df["City"].isnull().sum())

Missing City after cleaning: 0

In [ ]:
print("Customer duplicates:", customer_df.duplicated().sum())
print("Inventory duplicates:", inventory_df.duplicated().sum())
print("Product duplicates:", product_df.duplicated().sum())
print("Sales duplicates:", sales_df.duplicated().sum())

Customer duplicates: 0
Inventory duplicates: 0
Product duplicates: 0
Sales duplicates: 0

In [ ]:
print("Customer_ID duplicates:",
      customer_df["Customer_ID"].duplicated().sum())

print("Product_ID duplicates:",
      product_df["Product_ID"].duplicated().sum())

print("Sales Order_ID duplicates:",
      sales_df["Order_ID"].duplicated().sum())

print("Sales Customer_ID duplicates:",
      sales_df["Customer_ID"].duplicated().sum())

print("Sales Product_ID duplicates:",
      sales_df["Product_ID"].duplicated().sum())

Customer_ID duplicates: 0
Product_ID duplicates: 0
Sales Order_ID duplicates: 0
Sales Customer_ID duplicates: 4500
Sales Product_ID duplicates: 4920

In [ ]:
print("CUSTOMER DATA")
print("Age range:", customer_df["Age"].min(), "-", customer_df["Age"].max())
print("Total Orders range:",
      customer_df["Total_Orders"].min(), "-", customer_df["Total_Orders"].max())

print("\nSALES DATA")
print("Quantity range:", sales_df["Quantity"].min(), "-", sales_df["Quantity"].max())
print("Selling Price range:",
      sales_df["Selling_Price"].min(), "-", sales_df["Selling_Price"].max())
print("Cost Price range:",
      sales_df["Cost_Price"].min(), "-", sales_df["Cost_Price"].max())
print("Discount % range:",
      sales_df["Discount_Percent"].min(), "-", sales_df["Discount_Percent"].max())
print("Profit range:",
      sales_df["Profit"].min(), "-", sales_df["Profit"].max())

CUSTOMER DATA
Age range: 18 - 60
Total Orders range: 2 - 22

SALES DATA
Quantity range: 1 - 10
Selling Price range: 370 - 7700
Cost Price range: 241 - 4997
Discount % range: 0.0 - 20.0
Profit range: -728.0 - 23238.0

In [ ]:
sales_numeric = [
    "Quantity",
    "Selling_Price",
    "Cost_Price",
    "Gross_Sales",
    "Discount_Amount",
    "Revenue",
    "Total_Cost",
    "Profit",
    "Profit_Margin_Percent"
]

for col in sales_numeric:
    Q1 = sales_df[col].quantile(0.25)
    Q3 = sales_df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = ((sales_df[col] < lower) | (sales_df[col] > upper)).sum()

    print(f"{col}: {outliers} outliers")

Quantity: 52 outliers
Selling_Price: 0 outliers
Cost_Price: 53 outliers
Gross_Sales: 290 outliers
Discount_Amount: 338 outliers
Revenue: 279 outliers
Total_Cost: 239 outliers
Profit: 332 outliers
Profit_Margin_Percent: 24 outliers

In [ ]:
["Order_ID", "Product_Name", "Quantity", col]

['Order_ID', 'Product_Name', 'Quantity', 'Profit_Margin_Percent']

In [ ]:
["Order_ID", "Product_Name", "Quantity", "Quantity"]

['Order_ID', 'Product_Name', 'Quantity', 'Quantity']

In [ ]:
cols = [
    "Quantity",
    "Cost_Price",
    "Gross_Sales",
    "Revenue",
    "Profit",
    "Profit_Margin_Percent"
]

for col in cols:
    print(f"\n--- {col} ---")

    display(
        sales_df[["Order_ID", "Product_Name", col]]
        .sort_values(col, ascending=False)
        .head(5)
    )

--- Quantity ---

       Order_ID      Product_Name  Quantity
4868  ORD104868      Desk Lamp V2        10
2301  ORD102301   Office Chair V1        10
2121  ORD102121     Laptop Bag V3         9
2858  ORD102858   Water Bottle V3         9
2640  ORD102640  Printer Paper V3         9

--- Cost_Price ---

       Order_ID      Product_Name  Cost_Price
885   ORD100885  Printer Paper V1        4997
822   ORD100822  Printer Paper V1        4997
2154  ORD102154  Printer Paper V1        4997
4136  ORD104136  Printer Paper V1        4997
1965  ORD101965  Printer Paper V1        4997

--- Gross_Sales ---

       Order_ID      Product_Name  Gross_Sales
2640  ORD102640  Printer Paper V3        69300
2301  ORD102301   Office Chair V1        64600
4165  ORD104165  Printer Paper V3        61600
3610  ORD103610        Stapler V3        57360
950   ORD100950   Office Chair V1        51680

--- Revenue ---

       Order_ID      Product_Name  Revenue
2640  ORD102640  Printer Paper V3  65835.0
2301  ORD102301   Office Chair V1  64600.0
3610  ORD103610        Stapler V3  57360.0
4165  ORD104165  Printer Paper V3  52360.0
3119  ORD103119        Stapler V3  47680.5

--- Profit ---

       Order_ID      Product_Name   Profit
2640  ORD102640  Printer Paper V3  23238.0
3610  ORD103610        Stapler V3  20304.0
2301  ORD102301   Office Chair V1  18540.0
2405  ORD102405  Printer Paper V3  15492.0
3119  ORD103119        Stapler V3  15256.5

--- Profit_Margin_Percent ---

       Order_ID Product_Name  Profit_Margin_Percent
4912  ORD104912   USB Hub V1                  38.63
1022  ORD101022   USB Hub V1                  38.63
4923  ORD104923   USB Hub V1                  38.63
3050  ORD103050   USB Hub V1                  38.63
3281  ORD103281   USB Hub V1                  38.63

In [ ]:
print("Customer Data Types:")
print(customer_df.dtypes)

print("\nInventory Data Types:")
print(inventory_df.dtypes)

print("\nProduct Data Types:")
print(product_df.dtypes)

print("\nSales Data Types:")
print(sales_df.dtypes)

Customer Data Types:
Customer_ID                  object
Customer_Name                object
Age                           int64
Gender                       object
City                         object
Customer_Segment             object
Registration_Date            object
Total_Orders                  int64
Total_Spending              float64
Last_Purchase_Date           object
Total_Profit                float64
Days_Since_Last_Purchase      int64
Churn_Status                 object
dtype: object

Inventory Data Types:
Date              object
Product_ID        object
Product_Name      object
Category          object
Opening_Stock      int64
Units_Sold         int64
Stock_Received     int64
Closing_Stock      int64
dtype: object

Product Data Types:
Product_ID       object
Product_Name     object
Category         object
Cost_Price        int64
Selling_Price     int64
Initial_Stock     int64
dtype: object

Sales Data Types:
Order_ID                  object
Order_Date                object
Customer_ID               object
Product_ID                object
Product_Name              object
Category                  object
Quantity                   int64
Selling_Price              int64
Cost_Price                 int64
Discount_Percent         float64
Gross_Sales                int64
Discount_Amount          float64
Revenue                  float64
Total_Cost                 int64
Profit                   float64
Profit_Margin_Percent    float64
Payment_Mode              object
Sales_Channel             object
City                      object
dtype: object

In [ ]:
# Convert date columns from text to proper datetime format

customer_df["Registration_Date"] = pd.to_datetime(
    customer_df["Registration_Date"], dayfirst=True
)

customer_df["Last_Purchase_Date"] = pd.to_datetime(
    customer_df["Last_Purchase_Date"], dayfirst=True
)

inventory_df["Date"] = pd.to_datetime(
    inventory_df["Date"], dayfirst=True
)

sales_df["Order_Date"] = pd.to_datetime(
    sales_df["Order_Date"], dayfirst=True
)

print("Date conversion completed.")

Date conversion completed.

In [ ]:
print("Customer Registration:", customer_df["Registration_Date"].dtype)
print("Customer Last Purchase:", customer_df["Last_Purchase_Date"].dtype)
print("Inventory Date:", inventory_df["Date"].dtype)
print("Sales Order Date:", sales_df["Order_Date"].dtype)

Customer Registration: datetime64[ns]
Customer Last Purchase: datetime64[ns]
Inventory Date: datetime64[ns]
Sales Order Date: datetime64[ns]

In [ ]:
print("CUSTOMER DATA")
print("\nGender:")
print(customer_df["Gender"].value_counts(dropna=False))

print("\nCity:")
print(customer_df["City"].value_counts(dropna=False))

print("\nCustomer Segment:")
print(customer_df["Customer_Segment"].value_counts(dropna=False))


print("\nPRODUCT DATA")
print("\nCategory:")
print(product_df["Category"].value_counts(dropna=False))


print("\nINVENTORY DATA")
print("\nCategory:")
print(inventory_df["Category"].value_counts(dropna=False))


print("\nSALES DATA")
print("\nCategory:")
print(sales_df["Category"].value_counts(dropna=False))

print("\nPayment Mode:")
print(sales_df["Payment_Mode"].value_counts(dropna=False))

print("\nSales Channel:")
print(sales_df["Sales_Channel"].value_counts(dropna=False))

CUSTOMER DATA

Gender:
Gender
Female    265
Male      235
Name: count, dtype: int64

City:
City
Lucknow      63
Agra         60
Delhi        58
Prayagraj    52
Kanpur       51
Gurugram     50
Jaipur       43
Mumbai       42
Noida        42
Varanasi     39
Name: count, dtype: int64

Customer Segment:
Customer_Segment
Regular       276
Premium       118
Occasional    106
Name: count, dtype: int64

PRODUCT DATA

Category:
Category
Electronics    18
Office         18
Home           18
Accessories    18
Grocery         8
Name: count, dtype: int64

INVENTORY DATA

Category:
Category
Accessories    1110
Office         1092
Home           1087
Electronics    1066
Grocery         448
Name: count, dtype: int64

SALES DATA

Category:
Category
Accessories    1175
Office         1143
Home           1118
Electronics    1103
Grocery         461
Name: count, dtype: int64

Payment Mode:
Payment_Mode
UPI            2278
Card           1480
Cash            713
Net Banking     524
UPI               5
Name: count, dtype: int64

Sales Channel:
Sales_Channel
Online    2514
Store     2009
Phone      477
Name: count, dtype: int64

In [ ]:
print("Exact Payment Mode values:")

for value in sales_df["Payment_Mode"].dropna().unique():
    print(repr(value))

Exact Payment Mode values:
'Card'
'Cash'
'UPI'
'Net Banking'
'UPI '

In [ ]:
# Remove extra spaces from text columns

for df in [customer_df, inventory_df, product_df, sales_df]:
    text_columns = df.select_dtypes(include="object").columns

    for col in text_columns:
        df[col] = df[col].str.strip()

print("Extra spaces removed from text columns.")

Extra spaces removed from text columns.

In [ ]:
print(sales_df["Payment_Mode"].value_counts(dropna=False))

Payment_Mode
UPI            2283
Card           1480
Cash            713
Net Banking     524
Name: count, dtype: int64

In [ ]:
# Check whether missing Sales City can be recovered from Customer Data

missing_city = sales_df[sales_df["City"].isnull()]

print("Missing City rows:", len(missing_city))

display(
    missing_city[
        ["Order_ID", "Customer_ID", "Product_Name", "Revenue"]
    ]
)

Missing City rows: 0

Empty DataFrame
Columns: [Order_ID, Customer_ID, Product_Name, Revenue]
Index: []

In [ ]:
print("Sales City missing values:", sales_df["City"].isnull().sum())
print("Sales City unique values:")
print(sales_df["City"].value_counts(dropna=False))

Sales City missing values: 0
Sales City unique values:
City
Lucknow      664
Delhi        575
Agra         559
Gurugram     535
Prayagraj    533
Kanpur       496
Noida        463
Jaipur       422
Mumbai       389
Varanasi     364
Name: count, dtype: int64

In [ ]:
# Check for negative or zero values in important numerical columns

checks = {
    "Quantity": sales_df["Quantity"],
    "Selling_Price": sales_df["Selling_Price"],
    "Cost_Price": sales_df["Cost_Price"],
    "Discount_Percent": sales_df["Discount_Percent"],
    "Gross_Sales": sales_df["Gross_Sales"],
    "Revenue": sales_df["Revenue"],
    "Total_Cost": sales_df["Total_Cost"],
}

for name, column in checks.items():
    print(f"\n{name}")
    print("Negative values:", (column < 0).sum())
    print("Zero values:", (column == 0).sum())

Quantity
Negative values: 0
Zero values: 0

Selling_Price
Negative values: 0
Zero values: 0

Cost_Price
Negative values: 0
Zero values: 0

Discount_Percent
Negative values: 0
Zero values: 1218

Gross_Sales
Negative values: 0
Zero values: 0

Revenue
Negative values: 0
Zero values: 0

Total_Cost
Negative values: 0
Zero values: 0

In [ ]:
# Check loss-making orders

loss_orders = sales_df[sales_df["Profit"] < 0]

print("Loss-making orders:", len(loss_orders))
print("Maximum loss:", loss_orders["Profit"].min())

display(
    loss_orders[
        ["Order_ID", "Product_Name", "Category",
         "Quantity", "Revenue", "Total_Cost", "Profit"]
    ].sort_values("Profit").head(10)
)

Loss-making orders: 46
Maximum loss: -728.0

,Order_ID,Product_Name,Category,Quantity,Revenue,Total_Cost,Profit
3516,ORD103516,Keyboard V3,Electronics,4,13408.0,14136,-728.0
369,ORD100369,Wireless Mouse V3,Electronics,5,12840.0,13420,-580.0
3878,ORD103878,Keyboard V3,Electronics,3,10056.0,10602,-546.0
4553,ORD104553,Keyboard V3,Electronics,2,6704.0,7068,-364.0
2007,ORD102007,Power Bank V3,Accessories,3,4776.0,5064,-288.0
1043,ORD101043,Wireless Mouse V3,Electronics,2,5136.0,5368,-232.0
1273,ORD101273,Wireless Mouse V3,Electronics,2,5136.0,5368,-232.0
1418,ORD101418,Power Bank V3,Accessories,2,3184.0,3376,-192.0
4640,ORD104640,Power Bank V3,Accessories,2,3184.0,3376,-192.0
161,ORD100161,Storage Box V3,Home,3,5280.0,5469,-189.0

In [ ]:
print("Loss-making orders by Category:")

display(
    loss_orders.groupby("Category")
    .agg(
        Loss_Orders=("Profit", "count"),
        Total_Loss=("Profit", "sum")
    )
    .sort_values("Total_Loss")
)

Loss-making orders by Category:

             Loss_Orders  Total_Loss
Category
Electronics           15     -3048.0
Accessories           22     -1440.0
Home                   4      -417.0
Office                 1      -117.0
Grocery                4       -56.0

In [ ]:
print("Loss-making orders by Product:")

display(
    loss_orders.groupby(["Product_ID", "Product_Name"])
    .agg(
        Loss_Orders=("Profit", "count"),
        Total_Loss=("Profit", "sum")
    )
    .sort_values("Total_Loss")
)

Loss-making orders by Product:

                              Loss_Orders  Total_Loss
Product_ID Product_Name
P105       Keyboard V3                  3     -1638.0
P102       Wireless Mouse V3            5     -1276.0
P165       Power Bank V3                5      -864.0
P136       Water Bottle V1              3      -228.0
P171       Travel Pouch V3              7      -204.0
P157       Phone Case V1                5      -192.0
P141       Storage Box V3               1      -189.0
P163       Power Bank V1                5      -180.0
P127       Printer Paper V1             1      -117.0
P107       Headphones V2                1       -78.0
P106       Headphones V1                6       -56.0
P176       Tea V2                       4       -56.0

In [ ]:
print("Extreme Quantity values:")
display(
    sales_df[["Order_ID", "Product_Name", "Quantity", "Selling_Price", "Revenue", "Profit"]]
    .sort_values("Quantity", ascending=False)
    .head(10)
)

Extreme Quantity values:

       Order_ID       Product_Name  Quantity  Selling_Price  Revenue   Profit
4868  ORD104868       Desk Lamp V2        10           4970  42245.0   9075.0
2301  ORD102301    Office Chair V1        10           6460  64600.0  18540.0
2121  ORD102121      Laptop Bag V3         9           1980  16038.0   4743.0
2858  ORD102858    Water Bottle V3         9           2890  24709.5   7186.5
2640  ORD102640   Printer Paper V3         9           7700  65835.0  23238.0
4444  ORD104444  Wireless Mouse V1         9           3130  25353.0   5139.0
1371  ORD101371      Laptop Bag V2         8           2620  18864.0   4632.0
647   ORD100647      Power Bank V1         8            510   4080.0    656.0
4705  ORD104705        LED Bulb V3         8           2960  22496.0   5544.0
1958  ORD101958         USB Hub V2         8            980   6272.0   1016.0

In [ ]:
print("Extreme Selling Price values:")

display(
    sales_df[
        ["Order_ID", "Product_Name", "Quantity",
         "Selling_Price", "Cost_Price", "Revenue", "Profit"]
    ]
    .sort_values("Selling_Price", ascending=False)
    .head(10)
)

Extreme Selling Price values:

,Order_ID,Product_Name,Quantity,Selling_Price,Cost_Price,Revenue,Profit
4165,ORD104165,Printer Paper V3,8,7700,4733,52360.0,14496.0
4149,ORD104149,Printer Paper V3,1,7700,4733,6930.0,2197.0
4134,ORD104134,Printer Paper V3,4,7700,4733,27720.0,8788.0
4516,ORD104516,Printer Paper V3,3,7700,4733,23100.0,8901.0
4494,ORD104494,Printer Paper V3,2,7700,4733,14630.0,5164.0
4083,ORD104083,Printer Paper V3,1,7700,4733,7700.0,2967.0
2082,ORD102082,Printer Paper V3,1,7700,4733,7315.0,2582.0
2080,ORD102080,Printer Paper V3,3,7700,4733,20790.0,6591.0
1583,ORD101583,Printer Paper V3,4,7700,4733,24640.0,5708.0
1577,ORD101577,Printer Paper V3,4,7700,4733,27720.0,8788.0

In [ ]:
print("Extreme Cost Price values:")

display(
    sales_df[
        ["Order_ID", "Product_Name", "Quantity",
         "Selling_Price", "Cost_Price", "Revenue", "Profit"]
    ]
    .sort_values("Cost_Price", ascending=False)
    .head(10)
)

Extreme Cost Price values:

,Order_ID,Product_Name,Quantity,Selling_Price,Cost_Price,Revenue,Profit
885,ORD100885,Printer Paper V1,1,6100,4997,6100.0,1103.0
822,ORD100822,Printer Paper V1,4,6100,4997,24400.0,4412.0
2154,ORD102154,Printer Paper V1,2,6100,4997,10980.0,986.0
4136,ORD104136,Printer Paper V1,1,6100,4997,4880.0,-117.0
1965,ORD101965,Printer Paper V1,6,6100,4997,36600.0,6618.0
1986,ORD101986,Printer Paper V1,4,6100,4997,24400.0,4412.0
4121,ORD104121,Printer Paper V1,2,6100,4997,10980.0,986.0
675,ORD100675,Printer Paper V1,2,6100,4997,10980.0,986.0
4188,ORD104188,Printer Paper V1,2,6100,4997,12200.0,2206.0
135,ORD100135,Printer Paper V1,1,6100,4997,5795.0,798.0

In [ ]:
print("Extreme Revenue values:")

display(
    sales_df[
        ["Order_ID", "Product_Name", "Quantity",
         "Selling_Price", "Cost_Price", "Revenue", "Profit"]
    ]
    .sort_values("Revenue", ascending=False)
    .head(10)
)

Extreme Revenue values:

,Order_ID,Product_Name,Quantity,Selling_Price,Cost_Price,Revenue,Profit
2640,ORD102640,Printer Paper V3,9,7700,4733,65835.0,23238.0
2301,ORD102301,Office Chair V1,10,6460,4606,64600.0,18540.0
3610,ORD103610,Stapler V3,8,7170,4632,57360.0,20304.0
4165,ORD104165,Printer Paper V3,8,7700,4733,52360.0,14496.0
3119,ORD103119,Stapler V3,7,7170,4632,47680.5,15256.5
950,ORD100950,Office Chair V1,8,6460,4606,43928.0,7080.0
2405,ORD102405,Printer Paper V3,6,7700,4733,43890.0,15492.0
2566,ORD102566,Bluetooth Speaker V1,7,6930,4749,43659.0,10416.0
1923,ORD101923,Stapler V3,6,7170,4632,43020.0,15228.0
4146,ORD104146,Office Chair V1,7,6460,4606,42959.0,10717.0

In [ ]:
print("Extreme Profit values:")

display(
    sales_df[
        ["Order_ID", "Product_Name", "Quantity",
         "Selling_Price", "Cost_Price", "Revenue", "Profit"]
    ]
    .sort_values("Profit", ascending=False)
    .head(10)
)

Extreme Profit values:

,Order_ID,Product_Name,Quantity,Selling_Price,Cost_Price,Revenue,Profit
2640,ORD102640,Printer Paper V3,9,7700,4733,65835.0,23238.0
3610,ORD103610,Stapler V3,8,7170,4632,57360.0,20304.0
2301,ORD102301,Office Chair V1,10,6460,4606,64600.0,18540.0
2405,ORD102405,Printer Paper V3,6,7700,4733,43890.0,15492.0
3119,ORD103119,Stapler V3,7,7170,4632,47680.5,15256.5
1923,ORD101923,Stapler V3,6,7170,4632,43020.0,15228.0
4165,ORD104165,Printer Paper V3,8,7700,4733,52360.0,14496.0
4153,ORD104153,Bluetooth Speaker V1,6,6930,4749,41580.0,13086.0
3463,ORD103463,Stapler V3,6,7170,4632,40869.0,13077.0
2994,ORD102994,Stapler V3,5,7170,4632,35850.0,12690.0

In [ ]:
# Fill missing Discount_Percent with the median
discount_median = sales_df["Discount_Percent"].median()

sales_df["Discount_Percent"] = sales_df["Discount_Percent"].fillna(discount_median)

print("Missing Discount_Percent after cleaning:",
      sales_df["Discount_Percent"].isnull().sum())

print("Median Discount_Percent used:", discount_median)

Missing Discount_Percent after cleaning: 0
Median Discount_Percent used: 10.0

In [ ]:
# Verify sales calculations

sales_df["Calculated_Gross_Sales"] = (
    sales_df["Quantity"] * sales_df["Selling_Price"]
)

sales_df["Calculated_Discount_Amount"] = (
    sales_df["Calculated_Gross_Sales"] *
    sales_df["Discount_Percent"] / 100
)

sales_df["Calculated_Revenue"] = (
    sales_df["Calculated_Gross_Sales"] -
    sales_df["Calculated_Discount_Amount"]
)

print("Gross Sales mismatches:",
      (sales_df["Gross_Sales"] != sales_df["Calculated_Gross_Sales"]).sum())

print("Discount Amount mismatches:",
      (abs(sales_df["Discount_Amount"] -
           sales_df["Calculated_Discount_Amount"]) > 0.01).sum())

print("Revenue mismatches:",
      (abs(sales_df["Revenue"] -
           sales_df["Calculated_Revenue"]) > 0.01).sum())

Gross Sales mismatches: 0
Discount Amount mismatches: 0
Revenue mismatches: 0

In [ ]:
# Verify Profit calculation

sales_df["Calculated_Profit"] = (
    sales_df["Revenue"] - sales_df["Total_Cost"]
)

print(
    "Profit mismatches:",
    (abs(sales_df["Profit"] - sales_df["Calculated_Profit"]) > 0.01).sum()
)

Profit mismatches: 0

In [ ]:
# Final validation of important numerical columns

checks = {
    "Negative Quantity": (sales_df["Quantity"] < 0).sum(),
    "Negative Selling Price": (sales_df["Selling_Price"] < 0).sum(),
    "Negative Cost Price": (sales_df["Cost_Price"] < 0).sum(),
    "Invalid Discount (>100%)": (sales_df["Discount_Percent"] > 100).sum(),
    "Negative Revenue": (sales_df["Revenue"] < 0).sum(),
}

for check, count in checks.items():
    print(f"{check}: {count}")

Negative Quantity: 0
Negative Selling Price: 0
Negative Cost Price: 0
Invalid Discount (>100%): 0
Negative Revenue: 0

In [ ]:
print("FINAL MISSING VALUES")

for name, df in {
    "Customer": customer_df,
    "Inventory": inventory_df,
    "Product": product_df,
    "Sales": sales_df
}.items():
    print(f"\n{name}:")
    print(df.isnull().sum()[df.isnull().sum() > 0])

FINAL MISSING VALUES

Customer:
Series([], dtype: int64)

Inventory:
Series([], dtype: int64)

Product:
Series([], dtype: int64)

Sales:
Series([], dtype: int64)

In [ ]:
print("FINAL DUPLICATE CHECK")

print("Customer:", customer_df.duplicated().sum())
print("Inventory:", inventory_df.duplicated().sum())
print("Product:", product_df.duplicated().sum())
print("Sales:", sales_df.duplicated().sum())

FINAL DUPLICATE CHECK
Customer: 0
Inventory: 0
Product: 0
Sales: 0

In [ ]:
sales_df.drop(
    columns=[
        "Calculated_Gross_Sales",
        "Calculated_Discount_Amount",
        "Calculated_Revenue",
        "Calculated_Profit"
    ],
    inplace=True,
    errors="ignore"
)

print("Temporary verification columns removed.")

Temporary verification columns removed.

In [ ]:
# Save cleaned datasets

customer_df.to_csv("cleaned_customer_data.csv", index=False)
inventory_df.to_csv("cleaned_inventory_data.csv", index=False)
product_df.to_csv("cleaned_product_data.csv", index=False)
sales_df.to_csv("cleaned_sales_data.csv", index=False)

print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.

In [ ]:
# Final Data Quality Percentage

total_checks = 5
passed_checks = 5

accuracy_percentage = (passed_checks / total_checks) * 100

print(f"Final Data Quality Accuracy: {accuracy_percentage:.2f}%")

Final Data Quality Accuracy: 100.00%